@baseUrl = http://localhost:5278

### Test - GET - Récupération de tous les produits
GET {{baseUrl}}/api/produits
Accept: application/json

### Test - GET - Recuperation des produits selon la categorie
GET {{baseUrl}}/api/Produits?categorie=Audio
Accept: application/json

### Test - GET - Recuperation des produits selon la categorie avec une différente route
GET {{baseUrl}}/api/Produits/search?categorie=Audio
Accept: application/json

### Test - GET - Recuperation d'un produit avec un id
GET {{baseUrl}}/api/produits/2
Accept: application/json

### Test - GET - Recherche par catégorie, prix max et mot-clé
GET {{baseUrl}}/api/produits/search?categorie=Audio&prixMax=150&searchItem=blue
Accept: application/json

### Test - GET - Recherche par groupe de categorie
GET {{baseUrl}}/api/produits/group-by-categorie/
Accept: application/json

### Test - GET - Recherche par join entre produit et categorie
GET {{baseUrl}}/api/produits/produits-avec-categorie/
Accept: application/json

### Test - GET - Recherche des statistiques par prix
GET {{baseUrl}}/api/produits/stats-prix/
Accept: application/json

### Test - POST - Création d'un produit
POST {{baseUrl}}/api/produits
Content-Type: application/json

{
    "nom": "Souris",
    "prix": 19.99,
    "categorie": "Périphériques"
}

### Test - PUT - Modification d'un produit
PUT {{baseUrl}}/api/produits/2
Content-Type: application/json

{
    "id": 2,
    "nom": "Tablette",
    "prix": 109.99,
    "categorie": "Téléphonie"
}

### Test - DELETE - Supprimer un produit
DELETE {{baseUrl}}/api/produits/4
Accept: application/json

### Test 1 : Produits avec minPrix = 100, maxPrix = 800, catégorie = Audio
GET https://localhost:7286/api/Produits/filtre?minPrix=100&maxPrix=800&categorie=Audio
Accept: application/json

###

### Test 2 : Tous les produits au-dessus de 200 €
GET https://localhost:7286/api/Produits/filtre?minPrix=200
Accept: application/json

###

### Test 3 : Produits dans la catégorie Téléphonie uniquement
GET https://localhost:7286/api/Produits/filtre?categorie=Téléphonie
Accept: application/json

###

### Test 4 : Aucun filtre — doit retourner tous les produits
GET https://localhost:7286/api/Produits/filtre
Accept: application/json





